### ISSUE TITLE
`viking`: Automatically mark existing-but-mismatching functions as `M` or `m`

### ISSUE THREAD

**Issue by MonsterDruide1** [open-ead/nx-decomp-tools#20]
This would be helpful for games with existing debug info, to determinine which functions/classes have not been touched *at all* and which ones are being generated, but do not match yet.

**Comment by leoetlino** [comment]
sure, why not. I think we can extend the existing `update_matching_functions` logic to handle mismatching functions as well

**Comment by GRAnimated** [comment]
The only downside that I could see is a bunch of mismatching functions suddenly appearing in the BOTW/odyssey decomps from sead/agl (which would be correct behavior) but it would cause a pretty sudden jump in mismatches. At the same time, since the mismatching functions from sead/agl haven't been manually checked in either decomp, this would also produce a slight progress increase which could be appreciated.

**Comment by MonsterDruide1** [comment]
I don't see that as a downside at all, it just reflects the actual progress more accurately - if one has implemented something which does not match the behaviour on the other games, it should be obvious/displayed as such, and not be marked as "not implemented" until someone decides to manually check that function later, only to see it's been majorly done.
